<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FAQ [
<!ELEMENT FAQ (INFO, PART)>
<!ELEMENT INFO (TITULO, AUTOR, EMAIL, VERSION, FECHA)>
<!ELEMENT TITULO (#PCDATA)>
<!ELEMENT AUTOR (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT FECHA (#PCDATA)>
<!ELEMENT PART (Q+)>
<!ATTLIST PART number CDATA #IMPLIED>
<!ELEMENT Q (QTEXT, A)>
<!ATTLIST Q id CDATA #REQUIRED>
<!ELEMENT QTEXT (#PCDATA)>
<!ELEMENT A (#PCDATA)>
]>
<FAQ>
	<INFO>
		<TITULO> WINDOWS98? SOLO SI ME OBLIGAN! </TITULO>
		<AUTOR> Fernando Damián Lorenzo García </AUTOR>
		<EMAIL> Fer@yahoo.es </EMAIL>
		<VERSION> 1.0 </VERSION>
		<FECHA> 20.MAYO.99 </FECHA>
	</INFO>
	<PART number="1">
		<Q id="1">
			<QTEXT>¿Por qué tengo que instalar W95?</QTEXT>
			<A> A mi también me parece una buena pregunta.</A>
		</Q>
		<Q id="2">
			<QTEXT>Y de que me vale?</QTEXT>
			<A>Otra ingeniosa pregunta.</A>
		</Q>
	</PART>
</FAQ>
